{
  "services": [
    {
      "type": "web",
      "name": "sitara-hotel-backend",
      "env": "docker",
      "dockerfilePath": "./backend/Dockerfile",
      "dockerContext": "./backend",
      "envVars": [
        {
          "key": "SPRING_PROFILES_ACTIVE",
          "value": "prod"
        },
        {
          "key": "PORT",
          "value": "4040"
        }
      ]
    }
  ]
}

